name: YAML schema validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: nrkno/yaml-schema-validator-github-action@v5.1.0
        with:
          schema: yaml/schema.yaml
          target: yaml/terms/